$color = rgba(18, 20, 14, 1)
$inner_color = rgba(18, 20, 14, 0.66)
$outer_color = rgba(201, 128, 58, 1)
$font_color = rgba(206, 201, 189, 1)
$placeholder_color = rgba(206, 201, 189, 0.7)
$check_color = rgba(109, 125, 78, 1)
