background            #12140e
foreground            #cec9bd

# black
color0  #1c1e16
color8  #3a3d30

# red
color1  #a44a3f
color9  #c26350

# green
color2  #6d7d4e
color10 #8a9a63

# yellow
color3  #c9803a
color11 #e0a04f

# blue
color4  #4f6b74
color12 #7d97a1

# magenta
color5  #8a6a7a
color13 #a8899a

# cyan
color6  #6f8b86
color14 #8fa9a3

# white
color7  #cec9bd
color15 #e6e1d4
